#############################################################################
# Makefile for building: beediff
# Generated by qmake (3.0) (Qt 5.6.1)
# Project:  beediff.pro
# Template: app
# Command: /bin/qmake-qt5 -o Makefile beediff.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O3 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -Itmp -I/usr/lib64/qt5/mkspecs/linux-g++
QMAKE         = /bin/qmake-qt5
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = beediff1.0.0
DISTDIR = /home/david/code/beediff/src/tmp/beediff1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread -lXext -lX11 -lm
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = tmp/

####### Files

SOURCES       = BtStringTool.cpp \
		QBtBrowser.cpp \
		QBtColorDemo.cpp \
		QBtConfig.cpp \
		QBtConfigDialog.cpp \
		QBtConfigDiffProcess.cpp \
		QBtConfigOthers.cpp \
		QBtConfigTextViewer.cpp \
		QBtDiffInfo.cpp \
		QBtDiffProcess.cpp \
		QBtEventsController.cpp \
		QBtIndicator.cpp \
		QBtMainWindow.cpp \
		QBtNumeration.cpp \
		QBtOperator.cpp \
		QBtSaveQuestion.cpp \
		QBtSeparator.cpp \
		QBtSettings.cpp \
		QBtShared.cpp \
		QBtSyntax.cpp \
		QBtWorkspace.cpp \
		beediff.cpp qrc_beediff.cpp \
		tmp/moc_QBiConfigWidget.cpp \
		tmp/moc_QBtBrowser.cpp \
		tmp/moc_QBtColorDemo.cpp \
		tmp/moc_QBtConfig.cpp \
		tmp/moc_QBtConfigDialog.cpp \
		tmp/moc_QBtConfigDiffProcess.cpp \
		tmp/moc_QBtConfigOthers.cpp \
		tmp/moc_QBtConfigTextViewer.cpp \
		tmp/moc_QBtDiffProcess.cpp \
		tmp/moc_QBtEventsController.cpp \
		tmp/moc_QBtIndicator.cpp \
		tmp/moc_QBtMainWindow.cpp \
		tmp/moc_QBtNumeration.cpp \
		tmp/moc_QBtOperator.cpp \
		tmp/moc_QBtSaveQuestion.cpp \
		tmp/moc_QBtSeparator.cpp \
		tmp/moc_QBtSettings.cpp \
		tmp/moc_QBtSyntax.cpp \
		tmp/moc_QBtWorkspace.cpp
OBJECTS       = tmp/BtStringTool.o \
		tmp/QBtBrowser.o \
		tmp/QBtColorDemo.o \
		tmp/QBtConfig.o \
		tmp/QBtConfigDialog.o \
		tmp/QBtConfigDiffProcess.o \
		tmp/QBtConfigOthers.o \
		tmp/QBtConfigTextViewer.o \
		tmp/QBtDiffInfo.o \
		tmp/QBtDiffProcess.o \
		tmp/QBtEventsController.o \
		tmp/QBtIndicator.o \
		tmp/QBtMainWindow.o \
		tmp/QBtNumeration.o \
		tmp/QBtOperator.o \
		tmp/QBtSaveQuestion.o \
		tmp/QBtSeparator.o \
		tmp/QBtSettings.o \
		tmp/QBtShared.o \
		tmp/QBtSyntax.o \
		tmp/QBtWorkspace.o \
		tmp/beediff.o \
		tmp/qrc_beediff.o \
		tmp/moc_QBiConfigWidget.o \
		tmp/moc_QBtBrowser.o \
		tmp/moc_QBtColorDemo.o \
		tmp/moc_QBtConfig.o \
		tmp/moc_QBtConfigDialog.o \
		tmp/moc_QBtConfigDiffProcess.o \
		tmp/moc_QBtConfigOthers.o \
		tmp/moc_QBtConfigTextViewer.o \
		tmp/moc_QBtDiffProcess.o \
		tmp/moc_QBtEventsController.o \
		tmp/moc_QBtIndicator.o \
		tmp/moc_QBtMainWindow.o \
		tmp/moc_QBtNumeration.o \
		tmp/moc_QBtOperator.o \
		tmp/moc_QBtSaveQuestion.o \
		tmp/moc_QBtSeparator.o \
		tmp/moc_QBtSettings.o \
		tmp/moc_QBtSyntax.o \
		tmp/moc_QBtWorkspace.o
DIST          = /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KAuth.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KService.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_compositor.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_compositor_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_declarative.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_enginio.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_enginio_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_labscontrols_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_labstemplates_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_Solid.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/unix/x11.prf \
		/usr/lib64/qt5/mkspecs/features/unix/x11inc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/x11lib.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		beediff.pro BtStringTool.h \
		BtToken.h \
		QBiConfigWidget.h \
		QBtBrowser.h \
		QBtColorDemo.h \
		QBtConfig.h \
		QBtConfigDialog.h \
		QBtConfigDiffProcess.h \
		QBtConfigOthers.h \
		QBtConfigTextViewer.h \
		QBtDiffInfo.h \
		QBtDiffProcess.h \
		QBtEvent.h \
		QBtEventsController.h \
		QBtIndicator.h \
		QBtLineData.h \
		QBtMainWindow.h \
		QBtMarkerInfo.h \
		QBtNumeration.h \
		QBtOperator.h \
		QBtRange.h \
		QBtSaveQuestion.h \
		QBtSeparator.h \
		QBtSettings.h \
		QBtShared.h \
		QBtSyntax.h \
		QBtWorkspace.h BtStringTool.cpp \
		QBtBrowser.cpp \
		QBtColorDemo.cpp \
		QBtConfig.cpp \
		QBtConfigDialog.cpp \
		QBtConfigDiffProcess.cpp \
		QBtConfigOthers.cpp \
		QBtConfigTextViewer.cpp \
		QBtDiffInfo.cpp \
		QBtDiffProcess.cpp \
		QBtEventsController.cpp \
		QBtIndicator.cpp \
		QBtMainWindow.cpp \
		QBtNumeration.cpp \
		QBtOperator.cpp \
		QBtSaveQuestion.cpp \
		QBtSeparator.cpp \
		QBtSettings.cpp \
		QBtShared.cpp \
		QBtSyntax.cpp \
		QBtWorkspace.cpp \
		beediff.cpp
QMAKE_TARGET  = beediff
DESTDIR       = 
TARGET        = beediff


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: beediff.pro /usr/lib64/qt5/mkspecs/linux-g++/qmake.conf /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KAuth.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KService.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_compositor.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_compositor_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_declarative.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_enginio.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_enginio_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_labscontrols_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_labstemplates_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_Solid.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/unix/x11.prf \
		/usr/lib64/qt5/mkspecs/features/unix/x11inc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/x11lib.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		beediff.pro \
		beediff.qrc \
		/usr/lib64/libQt5Widgets.prl \
		/usr/lib64/libQt5Gui.prl \
		/usr/lib64/libQt5Core.prl
	$(QMAKE) -o Makefile beediff.pro
/usr/lib64/qt5/mkspecs/features/spec_pre.prf:
/usr/lib64/qt5/mkspecs/common/unix.conf:
/usr/lib64/qt5/mkspecs/common/linux.conf:
/usr/lib64/qt5/mkspecs/common/sanitize.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt5/mkspecs/common/g++-base.conf:
/usr/lib64/qt5/mkspecs/common/g++-unix.conf:
/usr/lib64/qt5/mkspecs/qconfig.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KAuth.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KBookmarks.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KCodecs.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KCompletion.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KConfigCore.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KConfigGui.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KConfigWidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KCoreAddons.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KIOCore.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KIOFileWidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KIOGui.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KIOWidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KItemViews.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KJobWidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KNTLM.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KService.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KWidgetsAddons.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KXmlGui.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_compositor.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_compositor_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_declarative.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_declarative_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_enginio.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_enginio_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_labscontrols_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_labstemplates_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_location.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_location_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_Solid.pri:
/usr/lib64/qt5/mkspecs/features/qt_functions.prf:
/usr/lib64/qt5/mkspecs/features/qt_config.prf:
/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib64/qt5/mkspecs/features/spec_post.prf:
/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt5/mkspecs/features/default_pre.prf:
/usr/lib64/qt5/mkspecs/features/resolve_config.prf:
/usr/lib64/qt5/mkspecs/features/default_post.prf:
/usr/lib64/qt5/mkspecs/features/unix/x11.prf:
/usr/lib64/qt5/mkspecs/features/unix/x11inc.prf:
/usr/lib64/qt5/mkspecs/features/unix/x11lib.prf:
/usr/lib64/qt5/mkspecs/features/warn_on.prf:
/usr/lib64/qt5/mkspecs/features/qt.prf:
/usr/lib64/qt5/mkspecs/features/resources.prf:
/usr/lib64/qt5/mkspecs/features/moc.prf:
/usr/lib64/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib64/qt5/mkspecs/features/uic.prf:
/usr/lib64/qt5/mkspecs/features/unix/thread.prf:
/usr/lib64/qt5/mkspecs/features/file_copies.prf:
/usr/lib64/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib64/qt5/mkspecs/features/exceptions.prf:
/usr/lib64/qt5/mkspecs/features/yacc.prf:
/usr/lib64/qt5/mkspecs/features/lex.prf:
beediff.pro:
beediff.qrc:
/usr/lib64/libQt5Widgets.prl:
/usr/lib64/libQt5Gui.prl:
/usr/lib64/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile beediff.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents beediff.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib64/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents BtStringTool.h BtToken.h QBiConfigWidget.h QBtBrowser.h QBtColorDemo.h QBtConfig.h QBtConfigDialog.h QBtConfigDiffProcess.h QBtConfigOthers.h QBtConfigTextViewer.h QBtDiffInfo.h QBtDiffProcess.h QBtEvent.h QBtEventsController.h QBtIndicator.h QBtLineData.h QBtMainWindow.h QBtMarkerInfo.h QBtNumeration.h QBtOperator.h QBtRange.h QBtSaveQuestion.h QBtSeparator.h QBtSettings.h QBtShared.h QBtSyntax.h QBtWorkspace.h $(DISTDIR)/
	$(COPY_FILE) --parents BtStringTool.cpp QBtBrowser.cpp QBtColorDemo.cpp QBtConfig.cpp QBtConfigDialog.cpp QBtConfigDiffProcess.cpp QBtConfigOthers.cpp QBtConfigTextViewer.cpp QBtDiffInfo.cpp QBtDiffProcess.cpp QBtEventsController.cpp QBtIndicator.cpp QBtMainWindow.cpp QBtNumeration.cpp QBtOperator.cpp QBtSaveQuestion.cpp QBtSeparator.cpp QBtSettings.cpp QBtShared.cpp QBtSyntax.cpp QBtWorkspace.cpp beediff.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_beediff.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_beediff.cpp
qrc_beediff.cpp: beediff.qrc \
		img/numbers.png \
		img/del_on_right.png \
		img/beediff.png \
		img/colors.png \
		img/fonts.png \
		img/question.png \
		img/qt.png \
		img/merge_to_left.png \
		img/to_left.png \
		img/remove.png \
		img/floppy.png \
		img/exit.png \
		img/to_right.png \
		img/merge_to_right.png \
		img/configure.png \
		img/sync.png \
		img/del_on_left.png
	/usr/lib64/qt5/bin/rcc -name beediff beediff.qrc -o qrc_beediff.cpp

compiler_moc_predefs_make_all: tmp/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) tmp/moc_predefs.h
tmp/moc_predefs.h: /usr/lib64/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O3 -Wall -W -dM -E -o tmp/moc_predefs.h /usr/lib64/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: tmp/moc_QBiConfigWidget.cpp tmp/moc_QBtBrowser.cpp tmp/moc_QBtColorDemo.cpp tmp/moc_QBtConfig.cpp tmp/moc_QBtConfigDialog.cpp tmp/moc_QBtConfigDiffProcess.cpp tmp/moc_QBtConfigOthers.cpp tmp/moc_QBtConfigTextViewer.cpp tmp/moc_QBtDiffProcess.cpp tmp/moc_QBtEventsController.cpp tmp/moc_QBtIndicator.cpp tmp/moc_QBtMainWindow.cpp tmp/moc_QBtNumeration.cpp tmp/moc_QBtOperator.cpp tmp/moc_QBtSaveQuestion.cpp tmp/moc_QBtSeparator.cpp tmp/moc_QBtSettings.cpp tmp/moc_QBtSyntax.cpp tmp/moc_QBtWorkspace.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) tmp/moc_QBiConfigWidget.cpp tmp/moc_QBtBrowser.cpp tmp/moc_QBtColorDemo.cpp tmp/moc_QBtConfig.cpp tmp/moc_QBtConfigDialog.cpp tmp/moc_QBtConfigDiffProcess.cpp tmp/moc_QBtConfigOthers.cpp tmp/moc_QBtConfigTextViewer.cpp tmp/moc_QBtDiffProcess.cpp tmp/moc_QBtEventsController.cpp tmp/moc_QBtIndicator.cpp tmp/moc_QBtMainWindow.cpp tmp/moc_QBtNumeration.cpp tmp/moc_QBtOperator.cpp tmp/moc_QBtSaveQuestion.cpp tmp/moc_QBtSeparator.cpp tmp/moc_QBtSettings.cpp tmp/moc_QBtSyntax.cpp tmp/moc_QBtWorkspace.cpp
tmp/moc_QBiConfigWidget.cpp: QBiConfigWidget.h \
		tmp/moc_predefs.h
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./tmp/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/david/code/beediff/src -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-redhat-linux -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/6.1.1/include -I/usr/local/include -I/usr/include QBiConfigWidget.h -o tmp/moc_QBiConfigWidget.cpp

tmp/moc_QBtBrowser.cpp: QBtSyntax.h \
		QBtBrowser.h \
		tmp/moc_predefs.h
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./tmp/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/david/code/beediff/src -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-redhat-linux -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/6.1.1/include -I/usr/local/include -I/usr/include QBtBrowser.h -o tmp/moc_QBtBrowser.cpp

tmp/moc_QBtColorDemo.cpp: QBtColorDemo.h \
		tmp/moc_predefs.h
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./tmp/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/david/code/beediff/src -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-redhat-linux -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/6.1.1/include -I/usr/local/include -I/usr/include QBtColorDemo.h -o tmp/moc_QBtColorDemo.cpp

tmp/moc_QBtConfig.cpp: QBtConfig.h \
		tmp/moc_predefs.h
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./tmp/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/david/code/beediff/src -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-redhat-linux -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/6.1.1/include -I/usr/local/include -I/usr/include QBtConfig.h -o tmp/moc_QBtConfig.cpp

tmp/moc_QBtConfigDialog.cpp: QBtConfigDialog.h \
		tmp/moc_predefs.h
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./tmp/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/david/code/beediff/src -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-redhat-linux -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/6.1.1/include -I/usr/local/include -I/usr/include QBtConfigDialog.h -o tmp/moc_QBtConfigDialog.cpp

tmp/moc_QBtConfigDiffProcess.cpp: QBiConfigWidget.h \
		QBtConfigDiffProcess.h \
		tmp/moc_predefs.h
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./tmp/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/david/code/beediff/src -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-redhat-linux -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/6.1.1/include -I/usr/local/include -I/usr/include QBtConfigDiffProcess.h -o tmp/moc_QBtConfigDiffProcess.cpp

tmp/moc_QBtConfigOthers.cpp: QBiConfigWidget.h \
		QBtConfigOthers.h \
		tmp/moc_predefs.h
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./tmp/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/david/code/beediff/src -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-redhat-linux -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/6.1.1/include -I/usr/local/include -I/usr/include QBtConfigOthers.h -o tmp/moc_QBtConfigOthers.cpp

tmp/moc_QBtConfigTextViewer.cpp: QBiConfigWidget.h \
		QBtConfigTextViewer.h \
		tmp/moc_predefs.h
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./tmp/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/david/code/beediff/src -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-redhat-linux -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/6.1.1/include -I/usr/local/include -I/usr/include QBtConfigTextViewer.h -o tmp/moc_QBtConfigTextViewer.cpp

tmp/moc_QBtDiffProcess.cpp: QBtRange.h \
		QBtShared.h \
		BtToken.h \
		QBtDiffInfo.h \
		QBtDiffProcess.h \
		tmp/moc_predefs.h
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./tmp/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/david/code/beediff/src -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-redhat-linux -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/6.1.1/include -I/usr/local/include -I/usr/include QBtDiffProcess.h -o tmp/moc_QBtDiffProcess.cpp

tmp/moc_QBtEventsController.cpp: QBtEvent.h \
		QBtEventsController.h \
		tmp/moc_predefs.h
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./tmp/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/david/code/beediff/src -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-redhat-linux -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/6.1.1/include -I/usr/local/include -I/usr/include QBtEventsController.h -o tmp/moc_QBtEventsController.cpp

tmp/moc_QBtIndicator.cpp: QBtRange.h \
		QBtShared.h \
		BtToken.h \
		QBtIndicator.h \
		tmp/moc_predefs.h
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./tmp/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/david/code/beediff/src -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-redhat-linux -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/6.1.1/include -I/usr/local/include -I/usr/include QBtIndicator.h -o tmp/moc_QBtIndicator.cpp

tmp/moc_QBtMainWindow.cpp: QBtMainWindow.h \
		tmp/moc_predefs.h
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./tmp/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/david/code/beediff/src -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-redhat-linux -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/6.1.1/include -I/usr/local/include -I/usr/include QBtMainWindow.h -o tmp/moc_QBtMainWindow.cpp

tmp/moc_QBtNumeration.cpp: QBtNumeration.h \
		tmp/moc_predefs.h
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./tmp/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/david/code/beediff/src -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-redhat-linux -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/6.1.1/include -I/usr/local/include -I/usr/include QBtNumeration.h -o tmp/moc_QBtNumeration.cpp

tmp/moc_QBtOperator.cpp: QBtMarkerInfo.h \
		QBtShared.h \
		QBtOperator.h \
		tmp/moc_predefs.h
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./tmp/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/david/code/beediff/src -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-redhat-linux -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/6.1.1/include -I/usr/local/include -I/usr/include QBtOperator.h -o tmp/moc_QBtOperator.cpp

tmp/moc_QBtSaveQuestion.cpp: QBtSaveQuestion.h \
		tmp/moc_predefs.h
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./tmp/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/david/code/beediff/src -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-redhat-linux -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/6.1.1/include -I/usr/local/include -I/usr/include QBtSaveQuestion.h -o tmp/moc_QBtSaveQuestion.cpp

tmp/moc_QBtSeparator.cpp: QBtSeparator.h \
		tmp/moc_predefs.h
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./tmp/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/david/code/beediff/src -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-redhat-linux -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/6.1.1/include -I/usr/local/include -I/usr/include QBtSeparator.h -o tmp/moc_QBtSeparator.cpp

tmp/moc_QBtSettings.cpp: QBtSettings.h \
		tmp/moc_predefs.h
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./tmp/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/david/code/beediff/src -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-redhat-linux -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/6.1.1/include -I/usr/local/include -I/usr/include QBtSettings.h -o tmp/moc_QBtSettings.cpp

tmp/moc_QBtSyntax.cpp: QBtSyntax.h \
		tmp/moc_predefs.h
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./tmp/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/david/code/beediff/src -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-redhat-linux -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/6.1.1/include -I/usr/local/include -I/usr/include QBtSyntax.h -o tmp/moc_QBtSyntax.cpp

tmp/moc_QBtWorkspace.cpp: QBtWorkspace.h \
		tmp/moc_predefs.h
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./tmp/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/david/code/beediff/src -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-redhat-linux -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/6.1.1/include -I/usr/local/include -I/usr/include QBtWorkspace.h -o tmp/moc_QBtWorkspace.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

tmp/BtStringTool.o: BtStringTool.cpp BtStringTool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/BtStringTool.o BtStringTool.cpp

tmp/QBtBrowser.o: QBtBrowser.cpp QBtBrowser.h \
		QBtSyntax.h \
		QBtLineData.h \
		QBtShared.h \
		QBtDiffProcess.h \
		QBtRange.h \
		BtToken.h \
		QBtDiffInfo.h \
		QBtConfig.h \
		QBtEventsController.h \
		QBtEvent.h \
		QBtOperator.h \
		QBtMarkerInfo.h \
		QBtNumeration.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/QBtBrowser.o QBtBrowser.cpp

tmp/QBtColorDemo.o: QBtColorDemo.cpp QBtColorDemo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/QBtColorDemo.o QBtColorDemo.cpp

tmp/QBtConfig.o: QBtConfig.cpp QBtConfig.h \
		QBtSettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/QBtConfig.o QBtConfig.cpp

tmp/QBtConfigDialog.o: QBtConfigDialog.cpp QBtConfigDialog.h \
		QBtConfigTextViewer.h \
		QBiConfigWidget.h \
		QBtConfigDiffProcess.h \
		QBtConfigOthers.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/QBtConfigDialog.o QBtConfigDialog.cpp

tmp/QBtConfigDiffProcess.o: QBtConfigDiffProcess.cpp QBtConfigDiffProcess.h \
		QBiConfigWidget.h \
		QBtEventsController.h \
		QBtEvent.h \
		QBtConfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/QBtConfigDiffProcess.o QBtConfigDiffProcess.cpp

tmp/QBtConfigOthers.o: QBtConfigOthers.cpp QBtConfigOthers.h \
		QBiConfigWidget.h \
		QBtConfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/QBtConfigOthers.o QBtConfigOthers.cpp

tmp/QBtConfigTextViewer.o: QBtConfigTextViewer.cpp QBtConfigTextViewer.h \
		QBiConfigWidget.h \
		QBtColorDemo.h \
		QBtConfig.h \
		QBtSettings.h \
		QBtEventsController.h \
		QBtEvent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/QBtConfigTextViewer.o QBtConfigTextViewer.cpp

tmp/QBtDiffInfo.o: QBtDiffInfo.cpp QBtDiffInfo.h \
		QBtRange.h \
		QBtShared.h \
		BtToken.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/QBtDiffInfo.o QBtDiffInfo.cpp

tmp/QBtDiffProcess.o: QBtDiffProcess.cpp QBtDiffProcess.h \
		QBtRange.h \
		QBtShared.h \
		BtToken.h \
		QBtDiffInfo.h \
		QBtBrowser.h \
		QBtSyntax.h \
		QBtConfig.h \
		QBtEventsController.h \
		QBtEvent.h \
		BtStringTool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/QBtDiffProcess.o QBtDiffProcess.cpp

tmp/QBtEventsController.o: QBtEventsController.cpp QBtEventsController.h \
		QBtEvent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/QBtEventsController.o QBtEventsController.cpp

tmp/QBtIndicator.o: QBtIndicator.cpp QBtIndicator.h \
		QBtRange.h \
		QBtShared.h \
		BtToken.h \
		QBtBrowser.h \
		QBtSyntax.h \
		QBtDiffInfo.h \
		QBtDiffProcess.h \
		QBtConfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/QBtIndicator.o QBtIndicator.cpp

tmp/QBtMainWindow.o: QBtMainWindow.cpp QBtMainWindow.h \
		QBtWorkspace.h \
		QBtShared.h \
		QBtConfig.h \
		QBtConfigDialog.h \
		QBtEventsController.h \
		QBtEvent.h \
		QBtSettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/QBtMainWindow.o QBtMainWindow.cpp

tmp/QBtNumeration.o: QBtNumeration.cpp QBtNumeration.h \
		QBtBrowser.h \
		QBtSyntax.h \
		QBtLineData.h \
		QBtShared.h \
		QBtConfig.h \
		QBtDiffProcess.h \
		QBtRange.h \
		BtToken.h \
		QBtDiffInfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/QBtNumeration.o QBtNumeration.cpp

tmp/QBtOperator.o: QBtOperator.cpp QBtOperator.h \
		QBtMarkerInfo.h \
		QBtShared.h \
		QBtBrowser.h \
		QBtSyntax.h \
		QBtLineData.h \
		QBtDiffProcess.h \
		QBtRange.h \
		BtToken.h \
		QBtDiffInfo.h \
		QBtConfig.h \
		QBtEventsController.h \
		QBtEvent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/QBtOperator.o QBtOperator.cpp

tmp/QBtSaveQuestion.o: QBtSaveQuestion.cpp QBtSaveQuestion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/QBtSaveQuestion.o QBtSaveQuestion.cpp

tmp/QBtSeparator.o: QBtSeparator.cpp QBtSeparator.h \
		QBtBrowser.h \
		QBtSyntax.h \
		QBtDiffProcess.h \
		QBtRange.h \
		QBtShared.h \
		BtToken.h \
		QBtDiffInfo.h \
		QBtConfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/QBtSeparator.o QBtSeparator.cpp

tmp/QBtSettings.o: QBtSettings.cpp QBtSettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/QBtSettings.o QBtSettings.cpp

tmp/QBtShared.o: QBtShared.cpp QBtShared.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/QBtShared.o QBtShared.cpp

tmp/QBtSyntax.o: QBtSyntax.cpp QBtSyntax.h \
		QBtConfig.h \
		QBtLineData.h \
		QBtShared.h \
		QBtDiffProcess.h \
		QBtRange.h \
		BtToken.h \
		QBtDiffInfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/QBtSyntax.o QBtSyntax.cpp

tmp/QBtWorkspace.o: QBtWorkspace.cpp QBtWorkspace.h \
		QBtBrowser.h \
		QBtSyntax.h \
		QBtConfig.h \
		QBtDiffProcess.h \
		QBtRange.h \
		QBtShared.h \
		BtToken.h \
		QBtDiffInfo.h \
		QBtEventsController.h \
		QBtEvent.h \
		QBtIndicator.h \
		QBtLineData.h \
		QBtOperator.h \
		QBtMarkerInfo.h \
		QBtSaveQuestion.h \
		QBtSeparator.h \
		QBtSettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/QBtWorkspace.o QBtWorkspace.cpp

tmp/beediff.o: beediff.cpp QBtShared.h \
		QBtMainWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/beediff.o beediff.cpp

tmp/qrc_beediff.o: qrc_beediff.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/qrc_beediff.o qrc_beediff.cpp

tmp/moc_QBiConfigWidget.o: tmp/moc_QBiConfigWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_QBiConfigWidget.o tmp/moc_QBiConfigWidget.cpp

tmp/moc_QBtBrowser.o: tmp/moc_QBtBrowser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_QBtBrowser.o tmp/moc_QBtBrowser.cpp

tmp/moc_QBtColorDemo.o: tmp/moc_QBtColorDemo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_QBtColorDemo.o tmp/moc_QBtColorDemo.cpp

tmp/moc_QBtConfig.o: tmp/moc_QBtConfig.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_QBtConfig.o tmp/moc_QBtConfig.cpp

tmp/moc_QBtConfigDialog.o: tmp/moc_QBtConfigDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_QBtConfigDialog.o tmp/moc_QBtConfigDialog.cpp

tmp/moc_QBtConfigDiffProcess.o: tmp/moc_QBtConfigDiffProcess.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_QBtConfigDiffProcess.o tmp/moc_QBtConfigDiffProcess.cpp

tmp/moc_QBtConfigOthers.o: tmp/moc_QBtConfigOthers.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_QBtConfigOthers.o tmp/moc_QBtConfigOthers.cpp

tmp/moc_QBtConfigTextViewer.o: tmp/moc_QBtConfigTextViewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_QBtConfigTextViewer.o tmp/moc_QBtConfigTextViewer.cpp

tmp/moc_QBtDiffProcess.o: tmp/moc_QBtDiffProcess.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_QBtDiffProcess.o tmp/moc_QBtDiffProcess.cpp

tmp/moc_QBtEventsController.o: tmp/moc_QBtEventsController.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_QBtEventsController.o tmp/moc_QBtEventsController.cpp

tmp/moc_QBtIndicator.o: tmp/moc_QBtIndicator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_QBtIndicator.o tmp/moc_QBtIndicator.cpp

tmp/moc_QBtMainWindow.o: tmp/moc_QBtMainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_QBtMainWindow.o tmp/moc_QBtMainWindow.cpp

tmp/moc_QBtNumeration.o: tmp/moc_QBtNumeration.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_QBtNumeration.o tmp/moc_QBtNumeration.cpp

tmp/moc_QBtOperator.o: tmp/moc_QBtOperator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_QBtOperator.o tmp/moc_QBtOperator.cpp

tmp/moc_QBtSaveQuestion.o: tmp/moc_QBtSaveQuestion.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_QBtSaveQuestion.o tmp/moc_QBtSaveQuestion.cpp

tmp/moc_QBtSeparator.o: tmp/moc_QBtSeparator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_QBtSeparator.o tmp/moc_QBtSeparator.cpp

tmp/moc_QBtSettings.o: tmp/moc_QBtSettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_QBtSettings.o tmp/moc_QBtSettings.cpp

tmp/moc_QBtSyntax.o: tmp/moc_QBtSyntax.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_QBtSyntax.o tmp/moc_QBtSyntax.cpp

tmp/moc_QBtWorkspace.o: tmp/moc_QBtWorkspace.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_QBtWorkspace.o tmp/moc_QBtWorkspace.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

